2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Configure stats pid to 29608
2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bestm\.config\wandb\settings
2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bestm\Desktop\Dev\AIKU\ABSA\ACSA-generation\wandb\settings
2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-30 04:23:02,514 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_MAMS_sentiment.py', 'program': 'C:\\Users\\bestm\\Desktop\\Dev\\AIKU\\ABSA\\ACSA-generation\\train_MAMS_sentiment.py'}
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\bestm\Desktop\Dev\AIKU\ABSA\ACSA-generation\wandb\run-20230830_042302-zlyu84u9\logs\debug.log
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\bestm\Desktop\Dev\AIKU\ABSA\ACSA-generation\wandb\run-20230830_042302-zlyu84u9\logs\debug-internal.log
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:init():547] calling init triggers
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:init():596] starting backend
2023-08-30 04:23:02,515 INFO    MainThread:29608 [wandb_init.py:init():600] setting up manager
2023-08-30 04:23:02,517 INFO    MainThread:29608 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-08-30 04:23:02,518 INFO    MainThread:29608 [wandb_init.py:init():606] backend started and connected
2023-08-30 04:23:02,521 INFO    MainThread:29608 [wandb_init.py:init():697] updated telemetry
2023-08-30 04:23:02,553 INFO    MainThread:29608 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-30 04:23:03,071 INFO    MainThread:29608 [wandb_run.py:_on_init():2180] communicating current version
2023-08-30 04:23:03,102 INFO    MainThread:29608 [wandb_run.py:_on_init():2189] got version response upgrade_message: "wandb version 0.15.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-08-30 04:23:03,102 INFO    MainThread:29608 [wandb_init.py:init():781] starting run threads in backend
2023-08-30 04:23:05,025 INFO    MainThread:29608 [wandb_run.py:_console_start():2159] atexit reg
2023-08-30 04:23:05,025 INFO    MainThread:29608 [wandb_run.py:_redirect():2014] redirect: wrap_raw
2023-08-30 04:23:05,025 INFO    MainThread:29608 [wandb_run.py:_redirect():2079] Wrapping output streams.
2023-08-30 04:23:05,025 INFO    MainThread:29608 [wandb_run.py:_redirect():2104] Redirects installed.
2023-08-30 04:23:05,026 INFO    MainThread:29608 [wandb_init.py:init():822] run started, returning control to user process
2023-08-30 04:23:33,811 ERROR   MainThread:29608 [wandb_init.py:init():1165] Invalid value for property project: True.
Traceback (most recent call last):
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_init.py", line 1143, in init
    wi.setup(kwargs)
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_init.py", line 303, in setup
    settings._apply_init(kwargs)
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 1751, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 1396, in update
    self.__dict__[key].update(settings.pop(key), source=source)
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 558, in update
    self._value = self._validate(self._preprocess(value))
  File "C:\Users\bestm\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_settings.py", line 531, in _validate
    raise SettingsValidationError(
wandb.sdk.wandb_settings.SettingsValidationError: Invalid value for property project: True.
2023-08-30 04:23:39,878 WARNING MsgRouterThr:29608 [router.py:message_loop():77] message_loop has been closed
